## Step 1 : Load the data

In [26]:
import wrds
import pandas as pd
from datetime import datetime

# Connect to WRDS
db = wrds.Connection(wrds_username='pherb127')

Loading library list...
Done

In [42]:
# Import Country Data
data=db.raw_sql("SELECT * FROM wrdsapps_windices.mwcountryreturns "
               "WHERE Country IN ('AUSTRALIA','FRANCE','GERMANY','JAPAN','SWITZERLAND','UNITED KINGDOM') "
               "AND Date BETWEEN '2002-01-01' AND '2024-12-31'")
data.to_csv('country_data.csv', sep=';', index=False)
data = pd.read_csv("country_data.csv", sep=';')

In [43]:
data.head()

   fic        date    country currency  mportret  mportretx
0  AUS  2002-01-31  AUSTRALIA      AUD  0.027358   0.027313
1  AUS  2002-02-28  AUSTRALIA      AUD -0.001832  -0.004358
2  AUS  2002-03-28  AUSTRALIA      AUD  0.005199  -0.001914
3  AUS  2002-04-30  AUSTRALIA      AUD -0.014302  -0.015424
4  AUS  2002-05-31  AUSTRALIA      AUD -0.000204  -0.001752

* mportret :

In [64]:
# Import US Data
# 2. Download the monthly value-weighted total return
crsp_vw = db.raw_sql(
    """
    SELECT
      date,
      vwretx,
      vwretd      
    FROM crsp.msi
    WHERE date BETWEEN '2002-01-01' AND '2024-12-31'
    """,
    date_cols=['date']
)

# 3. Save to CSV
crsp_vw.to_csv('crsp_value_weighted_returns.csv', sep=";", index=False)
crsp = pd.read_csv("crsp_value_weighted_returns.csv", sep=';')

In [65]:
crsp.head()

         date    vwretx    vwretd
0  2002-01-31 -0.016921 -0.015966
1  2002-02-28 -0.023066 -0.021700
2  2002-03-28  0.043730  0.044698
3  2002-04-30 -0.050504 -0.049600
4  2002-05-31 -0.011958 -0.010510

In [71]:
# Import 1 month t-bills data 
tbill = db.raw_sql(
    "select mcaldt, tmytm from crsp.tfz_mth_rf where kytreasnox = 2000001 and mcaldt>= '2002-01-01' and mcaldt<='2024-12-31'",
    date_cols=['date']
)

tbill.to_csv('tbill.csv', sep=";", index=False)
tbill = pd.read_csv("tbill.csv", sep=';')

In [72]:
tbill.head()

       mcaldt     tmytm
0  2002-01-31  1.689493
1  2002-02-28  1.732654
2  2002-03-28  1.709804
3  2002-04-30  1.752755
4  2002-05-31  1.689493